name: ChestNetworks
version: 1.0-SNAPSHOT
description: ChestNetworks allows you to create networks of chests; chests that sort items between themselves.
author: Zhincore
api-version: 1.18
main: eu.zhincore.chestnetworks.ChestNetworks

softdepend: [ChestSort]

commands:
  chestnet:
    description: Create or edit chest sort networks
    usage: Use /<command> help for help
    aliases: [cnet, chestnetwork, chestnetworks]
